pm25_importer:
  cron: "20 * * * *"
  class: Pm25Importer
  args:
  description: Import the PM2.5 concentrations from PDL cities.

#test_job:
  #every: 30s
  #class: TestJob
  #args:
  #description: Import the PM2.5 concentrations from PDL cities.
